Config = { 
	WeaponRecoil = {
		'WEAPON_PISTOL', 	--PISTOL	
		'WEAPON_PISTOL_MK2', 	--PISTOL MK2
		'WEAPON_COMBATPISTOL', -- COMBAT PISTOL
		'WEAPON_APPISTOL', -- AP PISTOL
		'WEAPON_PISTOL50', -- PISTOL .50
		'WEAPON_MICROSMG', -- MICRO SMG
		'WEAPON_SMG', -- SMG
		'WEAPON_SMG_MK2', -- SMG MK2
		'WEAPON_ASSAULTSMG', -- ASSAULT SMG
		'WEAPON_ASSAULTRIFLE', -- ASSAULT RIFLE
		'WEAPON_ASSAULTRIFLE_MK2',-- ASSAULT RIFLE MK2
		'WEAPON_CARBINERIFLE', -- CARBINE RIFLE
		'WEAPON_CARBINERIFLE_MK2', -- CARBINE RIFLE MK2
		'WEAPON_ADVANCED_RIFLE', -- ADVANCED RIFLE
		'WEAPON_MG', -- MG
		'WEAPON_COMBATMG', -- COMBAT MG
		'WEAPON_COMBATMG_MK2',-- COMBAT MG MK2
		'WEAPON_PUMPSHOTGUN', -- PUMP SHOTGUN
		'WEAPON_PUMPSHOTGUN_MK2',-- PUMP SHOTGUN MK2
		'WEAPON_SAWNOFFSHOTGUN', -- SAWNOFF SHOTGUN
		'WEAPON_ASSAULTSHOTGUN', -- ASSAULT SHOTGUN
		'WEAPON_BULLPUPSHOTGUN',-- BULLPUP SHOTGUN
		'WEAPON_STUNGUN',-- STUN GUN
		'WEAPON_SNIPERRIFLE',-- SNIPER RIFLE
		'WEAPON_HEAVYSNIPER',-- HEAVY SNIPER
		'WEAPON_HEAVYSNIPER_MK2', -- HEAVY SNIPER MK2
		'WEAPON_REMOTESNIPER',-- REMOTE SNIPER
		'WEAPON_GRENADELAUNCHER',-- GRENADE LAUNCHER
		'WEAPON_GRENADELAUCHER_SMOKE',-- GRENADE LAUNCHER SMOKE
		'WEAPON_RPG',-- RPG
		'WEAPON_STINGER',-- STINGER
		'WEAPON_MINIGUN',  -- MINIGUN
		'WEAPON_SNSPISTOL',-- SNS PISTOL
		'WEAPON_SNSPISTOL_MK2', -- SNS PISTOL MK2
		'WEAPON_GUSENBERG', -- GUSENBERG
		'WEAPON_SPECIALCARBINE',-- SPECIAL CARBINE
		'WEAPON_SPECIALCARBINE_MK2', -- SPECIAL CARBINE MK2
		'WEAPON_HEAVYPISTOL',-- HEAVY PISTOL		--new hashkey
		'WEAPON_BULLPUPRIFLE',-- BULLPUP RIFLE
		'WEAPON_BULLPUPRIFLE_MK2', -- BULLPUP RIFLE MK2
		'WEAPON_VINTAGEPISTOL', -- VINTAGE PISTOL
		'WEAPON_DOUBLEACTION', -- DOUBLE ACTION REVOLVER
		'WEAPON_MUSKET', -- MUSKET
		'WEAPON_HEAVYSHOTGUN', -- HEAVY SHOTGUN
		'WEAPON_MARKSMANRIFLE', -- MARKSMAN RIFLE
		'WEAPON_MARKSMANRIFLE_MK2', -- MARKSMAN RIFLE MK2
		'WEAPON_HOMINGLAUNCHER', -- HOMING LAUNCHER
		'WEAPON_FLAREGUN', -- FLARE GUN
		'WEAPON_COMBATPDW', -- COMBAT PDW
		'WEAPON_MARKSMANPISTOL', -- MARKSMAN PISTOL
	  	'WEAPON_RAILGUN', -- RAILGUN
		'WEAPON_MACHINEPISTOL',-- MACHINE PISTOL
		'WEAPON_REVOLVER', -- REVOLVER
		'WEAPON_REVOLVER_MK2', -- REVOLVER MK2
		'WEAPON_DBSHOTGUN', -- DOUBLE BARREL SHOTGUN
		'WEAPON_COMPACTRIFLE', -- COMPACT RIFLE
		'WEAPON_AUTOSHOTGUN',-- AUTO SHOTGUN
		'WEAPON_COMPACTLAUNCHER', -- COMPACT LAUNCHER
		'WEAPON_MINISMG', -- MINI SMG
	}
}
